repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format
        language: system
        types_or: [c, c++]
      - id: doc8
        name: doc8
        entry: python -m doc8 --config .doc8.ini
        language: system
        types: [rst]
      - id: isort
        name: isort
        entry: python -m isort
        language: system
        types_or: [python, pyi]
      - id: black
        name: black
        entry: python -m black
        language: system
        types_or: [python, pyi]
      - id: mypy
        name: mypy
        entry: python -m mypy --show-error-codes
        language: system
        types_or: [python, pyi]
        exclude: ^\.vscode/
        require_serial: true
      - id: flake8
        name: flake8
        entry: python -m flake8
        language: system
        types_or: [python, pyi]
